import { test, expect } from "@playwright/test";

test("SC-001–SC-006: sources, both forms, scope, pause, authoring", async ({ page, request }, info) => {
  const modules = await (await request.get("/api/v1/modules")).json();
  expect(modules.filter((m: { guidance_provenance: string }) => m.guidance_provenance === "verified_official")).toHaveLength(8);
  const sony = modules.find((m: { name: string }) => m.name === "sony_alpha");
  await request.put(`/api/v1/modules/${sony.id}`, { data: { status: "active" } });
  for (const device of await (await request.get("/api/v1/devices")).json()) await request.delete(`/api/v1/devices/${device.id}`);
  const external: string[] = [];
  await page.route("**/*", route => {
    const url = new URL(route.request().url());
    if (url.hostname !== "127.0.0.1") { external.push(url.href); return route.abort(); }
    return route.continue();
  });
  await page.goto("/modules");
  await expect(page.getByText("Sony Alpha cameras & lenses", { exact: true })).toBeVisible();
  await expect(page.getByText(/no positive RF-S release verified/)).toBeVisible();
  const card = page.locator('[data-slot="card"]').filter({ has: page.getByText("Sony Alpha cameras & lenses", { exact: true }) });
  await expect(card.getByText("0 linked devices")).toBeVisible();
  await card.getByRole("button", { name: "Inspect linked devices" }).click();
  await expect(card.getByText("No linked devices.")).toBeVisible();
  await card.locator("summary").focus();
  await page.keyboard.press("Enter");
  await expect(card.getByText("Internal name: sony_alpha")).toBeVisible();
  await card.getByRole("switch").click();
  await expect(card.getByText("Automatic off", { exact: true })).toBeVisible();

  await page.goto("/");
  await page.getByRole("button", { name: /Add.*Device/i }).first().click();
  await page.getByLabel("Name", { exact: true }).fill(`Camera ${info.project.name}`);
  await page.getByLabel("Source", { exact: true }).click();
  await page.getByRole("option", { name: /Sony Alpha cameras/ }).click();
  await expect(page.getByText(/Automatic monitoring is off/)).toBeVisible();
  await expect(page.getByLabel("Model", { exact: true })).toHaveAttribute("aria-describedby", "device-model-help");
  const order = await page.locator("#device-module, #device-model").evaluateAll(nodes => nodes.map(n => n.id));
  expect(order).toEqual(["device-module", "device-model"]);
  await page.getByLabel("Model", { exact: true }).fill("ILCE-7CM2");
  await page.getByRole("button", { name: "Search Version" }).click();
  await expect(page.getByLabel("Current Version")).toHaveValue("2.01");
  await page.getByRole("button", { name: "Add Device", exact: true }).click();
  await page.getByTitle("Edit device").click();
  await expect(page.getByLabel("Source", { exact: true })).toBeVisible();
  await expect(page.getByText(/Automatic monitoring is off/)).toBeVisible();
  await page.getByLabel("Current Version").fill("operator typed");
  await page.getByLabel("Model", { exact: true }).fill("near-match unknown");
  await page.getByRole("button", { name: "Search Version" }).click();
  await expect(page.getByRole("alert")).toContainText("product_not_found");
  await page.getByLabel("Source", { exact: true }).click();
  await page.getByRole("option", { name: "Nikon Z-series cameras" }).click();
  await expect(page.getByRole("alert")).toHaveCount(0);
  await expect(page.getByLabel("Current Version")).toHaveValue("operator typed");
  await expect(page.getByRole("link", { name: /Model naming/ })).toHaveAttribute("href", "https://downloadcenter.nikonimglib.com/en/index.html");
  await expect(page.getByRole("link", { name: /scrape endpoint/ })).toHaveAttribute("href", /product_data.xml/);
  await page.getByRole("button", { name: "Cancel", exact: true }).click();

  await page.goto("/modules");
  await card.getByRole("button", { name: "Inspect linked devices" }).click();
  await expect(card.getByText("1 linked devices")).toBeVisible();
  await expect(card.getByRole("listitem")).toContainText(`Camera ${info.project.name}`);
  const created = await request.post("/api/v1/devices", { data: { name: "External member", model: "ILCE-7CM2", module_id: sony.id, current_version: "1" } });
  expect(created.ok()).toBe(true);
  const extraDevice = await created.json();
  await page.getByRole("button", { name: "Refresh sources", exact: true }).click();
  await expect(card.getByText("2 linked devices")).toBeVisible();
  await expect(card.getByRole("listitem").filter({ hasText: "External member" })).toBeVisible();
  await request.delete(`/api/v1/devices/${extraDevice.id}`);
  await page.getByRole("button", { name: "Refresh sources", exact: true }).click();
  await expect(card.getByText("1 linked devices")).toBeVisible();
  await expect(card.getByText(/and devices linked later/)).toBeVisible();
  const create = page.getByRole("button", { name: "Create a Module", exact: true });
  await create.focus();
  await page.keyboard.press("Enter");
  await expect(create).toHaveAttribute("aria-expanded", "true");
  await expect(page.getByText("STARTER_TEMPLATE.py", { exact: true })).toBeVisible();
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: /STARTER_TEMPLATE.py/ }).click();
  expect((await download).suggestedFilename()).toBe("STARTER_TEMPLATE.py");
  await expect(page.getByText(/Share your reviewed Python file/)).toBeVisible();
  await page.getByRole("button", { name: "Upload Module", exact: true }).click();
  await expect(page.getByText(/unsandboxed, user-vetted code/)).toBeVisible();
  const name = `custom_${info.project.name}.py`;
  const base = 'MODULE_VERSION="1"\nSUPPORTED_DEVICE_TYPE="camera"\ndef check_firmware(a,b,c): return {"latest_version":"1"}\n';
  await page.getByLabel("Python module file", { exact: true }).setInputFiles({ name, mimeType: "text/x-python", buffer: Buffer.from(base + 'SOURCE_DISPLAY_NAME="' + "x".repeat(121) + '"\n') });
  await page.getByRole("button", { name: "Upload Module", exact: true }).click();
  await expect(page.getByText("Module Validation Failed")).toBeVisible();
  await expect(page.getByText(/use text of at most 120/)).toBeVisible();
  await expect(page.getByRole("button", { name: "Copy for AI" })).toBeVisible();
  await page.getByLabel("Python module file", { exact: true }).setInputFiles({ name, mimeType: "text/x-python", buffer: Buffer.from(base) });
  await page.getByRole("button", { name: "Upload Module", exact: true }).click();
  await expect(page.getByText("Module Uploaded Successfully")).toBeVisible();
  const uploaded = await (await request.get("/api/v1/modules")).json();
  expect(uploaded.find((m: { name: string }) => m.name === name.replace(".py", "")).guidance_provenance).toBe("custom");
  await expect(page.locator("body")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(external).toEqual([]);
  await page.screenshot({ path: `test-results/source-guidance-${info.project.name}.png`, fullPage: true });
  await request.put(`/api/v1/modules/${sony.id}`, { data: { status: "active" } });
});
